config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'tweets#index'
resources :tweets
resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
 end
  end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]
  
  def index
   @tweets=Tweet.all
  end

  def new
   @tweet=Tweet.new
  end

 def create
   @tweet = Tweet.create(tweet_params)
   @tweet = Tweet.new(tweet_params)
 end

 def destroy
   tweet = Tweet.find(params[:id])
   tweet.destroy
 end

 def edit
   
 end

 def update
   tweet=Tweet.find(params[:id])
   tweet.update(tweet_params)
 end

 def show
  

 end


 private
 def tweet_params
   params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
 end
 
 def set_tweet
  @tweet = Tweet.find(params[:id])
end


 def move_to_index
  unless user_signed_in?
  redirect_to action: :index 
 end
  end
 

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @tweets = current_user.tweets 
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <body>
   <header class="header">
     <div class="header__bar row">
      <h1 class="grid-6"><a href="/">ChatChat</a></h1>
       <% if user_signed_in? %>
        <div class="user_nav grid-6"> 
          <span><%= current_user.nickname %>
           <ul class="user__info"> 
            <li>
              <%= link_to "マイページ", "/users/#{current_user.id}" %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> 
            </li>
          </ul> 
        </span>
             <%= link_to "投稿する", new_tweet_path, class: "post" %> 
      </div>
    <% else %>
   <div class="grid-6">
      <%= link_to "ログイン", new_user_session_path, class: "post" %>
      <%= link_to "新規登録", new_user_registration_path, class: "post" %> </div>
    <% end %> 
  </div>
</header>
    <%= yield %>
     <footer>
      <p>
        Copyright ChatChat 2021.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
   <h3>投稿が完了しました</h3>
   <a class ="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
 <div class="success">
  <h3>削除が完了しました。</h3>
  <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    
      <h3>編集する</h3>
       
       <%= form_with(model: @tweet, local: true) do |form| %>
     
     <%= form.file_field :image, id:"tweet-image"  %>
     <%= form.text_area :text,placeholder: "text",rows: "10" %>
     <%= form.submit "SEND" %>
   <%end%>
   
  </div>
</div>

app/views/tweets/index.html.erb
<div class="contents row">
  <% @tweets.each do |tweet| %>
   <div class="content_post" style="background-image: url(<%= tweet.image %>);"> <div class="more">

     <span>
       <%= image_tag 'arrow_top.png' %>
     </span> 
   <ul class="more_list">
    <li>
    <%= link_to '詳細', tweet_path(tweet.id), method: :get %>

    <% if user_signed_in? && current_user.id == tweet.user_id %>
     <%= link_to '編集', edit_tweet_path(tweet.id), method: :get %>
     <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
    </li>
    <% end %>
   </ul>
</div>


<p><%= tweet.text %></p> 
<span class="name">

<span>投稿者</span><%= tweet.user.nickname %>

 </span>
</div> 
<% end %>
</div>  


          
          

app/views/tweets/new.html.erb
<div class="contents row ">
 <div class="container">
   <h3>投稿する</h3>

      
   <%= form_with(model: @tweet, local: true) do |form| %>
     
     <%= form.file_field :image, id:"tweet-image"  %>

     <%= form.text_area :text,placeholder: "text",rows: "10" %>
     <%= form.submit "SEND" %>


   <%end%>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
 <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
  <% if user_signed_in? && current_user.id == @tweet.user_id %>
  <div class="more">
   <span><%= image_tag 'arrow_top.png' %></span> 
    <ul class="more_list">
     <li>
       <%= link_to '編集', edit_tweet_path(@tweet.id), method: :get %>
     </li>

     <li>
       <%= link_to '削除', tweet_path(@tweet.id), method: :delete %> 
     </li>
   </ul>   
  </div>
<% end %>
  <p><%= @tweet.text %></p>
   <span class="name">

 <span>投稿者</span><%= @tweet.user.nickname %>

  </span>
 </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
<p><%= @nickname %>さんの投稿一覧</p> 
<% @tweets.each do |tweet| %>
<div class="content_post" style="background-image: url(<%= tweet.image %>);"> 
<p><%= tweet.text %></p>

</div>
 <% end %>
</div>